In [ ]:
## Numpy array and basics

In [1]:
import numpy as np

## Creating array from list

In [5]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D array:", arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array:", arr_2d)

1D array: [1 2 3 4 5]
2D array: [[1 2 3]
 [4 5 6]]


### List vs numpy array

In [7]:
py_list = [1, 2, 3]
print("Python list multiplication", py_list * 2)

np_array = np.array([1, 2, 3])
print("Python array multiplication", np_array * 2)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time: ", time.time() - start)

start = time.time()
np_array = np.arange(1000000 * 2)
print("\n Numpy operation time: ", time.time() - start)


Python list multiplication [1, 2, 3, 1, 2, 3]
Python array multiplication [2 4 6]

 List operation time:  0.06440472602844238

 Numpy operation time:  0.004216432571411133


## Creating array from scratch

In [67]:
zeros = np.zeros((3, 4))
print("zeros array: \n", zeros)

ones = np.ones((2, 3))
print("ones array: \n", ones)

full = np.full((2, 2), 7)
print("full array: \n", full)

random = np.random.random((2, 3))
print("random array: \n", random)

sequence = np.arange(0, 11, 3)
print("sequence array: \n", sequence)


zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[7 7]
 [7 7]]
random array: 
 [[0.76718552 0.0244278  0.40755155]
 [0.66084111 0.42875948 0.02751148]]
sequence array: 
 [0 3 6 9]


### Vector, Matrix and Tensor

In [68]:
vector = np.array([1, 2, 3])
print("Vector: ", vector)

matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
print("Matrix: ", matrix)


tensor = np.array([[[1, 2], [3, 4]],
                   [[5, 6], [7, 8]]])
print("Tensor: ", tensor)


Vector:  [1 2 3]
Matrix:  [[1 2 3]
 [4 5 6]]
Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array properties            

In [69]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Shape ", arr.shape)
print("Dimension ", arr.ndim)
print("Size ", arr.size)
print("DType ", arr.dtype)

Shape  (2, 3)
Dimension  2
Size  6
DType  int64
